### ISSUE TITLE
Needs a LICENSE

### ISSUE THREAD

**Issue by tmarble** [clojure-rs/ClojureRS#1]
As a Rust developer (and ex-Clojure developer) i am quite interested in your repo!

However it all depends on how you want to collaborate: is it "about you" or "about us"?

**Comment by Tko1** [comment]
I appreciate it!  The project will be going with the same license as Clojure, namely, the EPL 1.0  .  Someone shared this project sooner than I expected (although I'm certainly not complaining,  I enjoy seeing the interest),  and I originally was not going to decide for sure likely until this weekend,  as I wanted to do some more reading on the exact nuance of the licenses that I've put off for years. If you have another suggestion and reasoning, I am always all ears, and will not close this / add the license just yet.

**Comment by tmarble** [comment]
Well I do have a lot of opinions about this.. and, to be fair, there are a bunch of resources
to help you decide like github's own https://choosealicense.com/

Generally speaking the big choice is do you want to "share and give me credit"
(with permissive licenses like MIT or Apache 2) or "share and share alike"
(with "restrictive" licenses like the GPL). You always want a license that
is approved by the OSI and probably one from the Popular list: https://opensource.org/licenses

In any case it's a good idea to have a license with a (anti) patent provision like Apache 2 or GPLv3.

Is there a _really strong_ motivation to use EPL? I think that's one of the most unfortunate bits about Clojure because the EPL was designed to be GPL incompatible. Discussing open source license compatability theory quickly gets very complex.

Personally I lean towards "share and share alike" licenses whenever possible. I realize that many
Clojure developers (especially those from VC funded startups) come from a culture that it's very strongly against "share and share alike". With this in mind and aiming for broad adoption then maybe a permissive license like Apache 2 is a safe choice (it's at least much better than the EPL).

It is worth noting that Rust itself is in the "share and give me credit" camp with [MIT or Apache 2](https://github.com/rust-lang/rust#license). This "disjunctive" combo of licenses (pick MIT or Apache 2) seems odd because it feels like that would weaken the stronger patent provisions of Apache 2 (why not just say MIT then?). In any case I am not a lawyer (IANAL) and this is not legal advice (TINLA).

As long as the number of contributors is small and all of them can reach consensus you can change your mind later.

Allow me to suggest, as well, an "inbound=outbound" policy (and for extra credit the DCO).  FFI see  a [CONTRIBUTING](https://github.com/dollabs/pamela/blob/master/CONTRIBUTING.md) document that I have worked on.

I'm always happy to discuss open source licensing!

**Comment by jbwyatt4** [comment]
Hi @Tko1 

Your project looks very interesting and thank you for keeping legal compatibility with Clojure libraries.

I would appreciate a removable exception to the EPL allowing relicense under the GPL v2 and higher to maintain GPL compatibility.

Or dual license it under EPL v1/Apache2 which gives GPL v3 compatibility + compatibility with the greater Rust community. Thank you.

https://opensource.stackexchange.com/questions/4771/gpl3-project-with-epl-library

**Comment by arbroween** [comment]
Hi there !

I don't know if it's the right place, if not I'm sorry. I also just came across your project which seems really cool and of special interest to me.

I got the same idea about implementing Clojure in Rust and I have been working on a Clojure implementation of my own in the last few weeks. It is not as advanced as yours (I mostly only have the parser part so far) and I have only used the standard library. You want to take a look you can find it at https://github.com/arbroween/claire

Would you be interested to collaborate or take contributors ? :)

**Comment by Tko1** [comment]
Hey guys, I appreciate all the help, I've gone with Apache2
