### ISSUE TITLE
bug: empty string can no longer be parsed

### ISSUE THREAD

**Issue by erkkikeranen** [clojure-rs/ClojureRS#59]
- [ ] make sure `""` can be parsed by the reader
- [ ] add unit test

```
clojure.core=> ""
#Condition["Reader Error: could not read next form; Error(("\"\"", Tag))"]
```

**Comment by Tko1** [comment]
Bug on Feature/value regex, to be fixed before merging 

(Let me know if it has shown up anywhere else, although I don't believe it would be)
